# Generated by Django 3.1.7 on 2021-03-04 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='good_name')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='good_description')),
                ('category', models.TextField(verbose_name='good_category')),
                ('remainder', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='remainder')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
