# Generated by Django 3.1.7 on 2021-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Good', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.TextField(choices=[('new', 'новые'), ('old', 'просроченные')], verbose_name='good_category'),
        ),
        migrations.AlterModelTable(
            name='good',
            table='goods',
        ),
    ]
