# Generated by Django 3.1.7 on 2021-04-02 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210305_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='remainder',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='remainder'),
        ),
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='webapp.good', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
                'db_table': 'good_in_cart',
            },
        ),
    ]
