# Generated by Django 3.1.7 on 2021-04-05 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210305_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='контакты')),
                ('adress', models.CharField(max_length=50, verbose_name='адрес')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='good',
            name='remainder',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='remainder'),
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ManyToManyField(related_name='order', to='webapp.Good'),
        ),
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='webapp.good', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
            },
        ),
    ]
