# Generated by Django 3.1.7 on 2021-04-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_order_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_good', to='webapp.order'),
        ),
    ]
